[package]
name = "Rust-Assitant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openai-api = "0.1.4"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }

